Autox
iter8-tools/iter8 pull request #1319
Opened 2022-08-22 15:52 UTC by Alan-Cha

2022-08-24 19:39 UTC, sriumcp requested changes
Please see change requests.

2022-08-24 19:39 UTC, sriumcp commented on autox/service.go
> +package autox
Rename `service.go` to `watcher.go`. 

Remove sub folder `watcher`. Put everything under the `autox` package.

2022-08-24 19:39 UTC, sriumcp commented on autox/service.go
> +// service.go - entry point for A/B(/n) service; starts controller watching resources
Fix.

2022-08-24 19:39 UTC, sriumcp commented on autox/service.go
> +// service.go - entry point for A/B(/n) service; starts controller watching resources
Also add `doc.go` for package level documentation.

2022-08-24 19:39 UTC, sriumcp commented on autox/service.go
> +// service.go - entry point for A/B(/n) service; starts controller watching resources
FYI. https://go.dev/blog/godoc

2022-08-24 19:39 UTC, sriumcp commented on cmd/autox.go
> +Run the Iter8 AutoX service.
`autox controller` everywhere instead of `autox service`.

2022-08-24 19:39 UTC, sriumcp commented on action/autox.go
> +package action
No need for this file.

2022-08-24 19:39 UTC, sriumcp commented on cmd/autox.go
> +			return actor.LocalRun()
Call `autox.Start` here (instead of actor.LocalRun).

2022-08-31 20:29 UTC, Alan-Cha commented
See #1328

2022-08-31 20:29 UTC, closed without merging