check existence of custom resources
iter8-tools/iter8 pull request #1345
Opened 2022-09-29 22:28 UTC by sriumcp

Signed-off-by: Srinivasan Parthasarathy <spartha@us.ibm.com>

2022-09-30 12:11 UTC, kalantar requested changes
I believe you need to modify `_k-role.tpl` as well to git Iter8 permission to get the resource.

2022-09-30 12:52 UTC, sriumcp commented
> I believe you need to modify `_k-role.tpl` as well to git Iter8 permission to get the resource.

Absolutely. Thanks for catching. Fixed now.

2022-09-30 12:54 UTC, kalantar approved these changes

2022-10-03 15:03 UTC, Alan-Cha approved these changes

2022-10-03 15:04 UTC, merged