Ability to set the iter8 version to install as an input parameter
iter8-tools/iter8 pull request #1377
Opened 2022-11-30 22:10 UTC by chgl

Tested in a random repository over at: https://github.com/chgl/release-please-test/actions/runs/3587492586/jobs/6037900545
See the changes at https://github.com/chgl/release-please-test/pull/8/files. The second step is expected to fail.

2022-11-30 23:06 UTC, sriumcp commented on action.yaml
> +        VERSION: ${{ inputs.version }}
Is `env.Version` still required? Shouldn't we replace `env.Version` with `inputs.version`?

2022-12-01 00:59 UTC, sriumcp commented on action.yaml
> +        VERSION: ${{ inputs.version }}
Also, we have gone back-and-forth on the following idea. But, SHA pinning of Iter8 action seems like a good reason to have a separate repo for the iter8 action altogether. Then we can ... 

```yaml
-uses: iter8-tools/iter8-action@<sha commit>
```

And within the `action.yaml`, we can fix the Iter8 release that is getting used to install Iter8!

FYI @kalantar.

2022-12-01 15:34 UTC, kalantar commented
The logic to find a release will require modification as @sriumcp suggests. However, the code to download the iter8 binary depends on the release as well. Can we download the asset by SHA?

2022-12-01 16:00 UTC, kalantar commented
The logic to select the release might be simplied (remove the then) as:
```
if [ -z $RELEASE ] || [ $RELEASE = "stable" ]; then
  REL=$(curl --silent "https://api.github.com/repos/iter8-tools/iter8/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
fi
if [ -z $REL ]; then
  REL=$(curl -s "https://api.github.com/repos/iter8-tools/iter8/releases" | jq -r '.[] | .tag_name' | grep -w $RELEASE | sort -Vr | head -1)
fi
if [ -z $REL ]; then
  REL=$(curl -s "https://api.github.com/repos/iter8-tools/iter8/tags" | jq -r '.[] | .commit.sha' | grep -w $RELEASE | head -1)
  REL=$(curl -s "https://api.github.com/repos/iter8-tools/iter8/tags" | jq -r --arg RELEASE $RELEASE '.[] | select(.commit.sha==$RELEASE) | .name')
fi
if [ -z $REL ]; then
  echo "Invalid release specified: $RELEASE"
  exit 1
fi
echo "Installing Iter8 version $REL"
```

2022-12-01 16:12 UTC, chgl commented on action.yaml
> +        VERSION: ${{ inputs.version }}
> Is env.VERSION still required? Should we replace env.VERSION with inputs.version?

Not necessarily, I can definitely replace env.VERSION - the current way just keeps the number of changes minimal. Should I?

> Should action.yaml change along the below lines to make the SHA pinning work (very rough attempt below)?

I think that's a really good approach - instead of finding the release from its tag, find the tag from the commit sha. It's generally possible that one might specify a commit sha that doesn't correspond to a git tag (and therefore a release), however most tools to auto-update a digest-pinned action will follow git tags anyways so it shouldn't be a problem.

2022-12-02 04:09 UTC, sriumcp requested changes

2022-12-02 04:09 UTC, sriumcp commented on action.yaml
> +        VERSION: ${{ inputs.version }}
Combining all of the above discussion with [this suggestion](https://github.com/iter8-tools/iter8/pull/1377#issuecomment-1333988464) ... could we please modify the `action.yaml` in this PR so that it looks as follows. I realize the changes below are more than minimal, but SHA pinning is clearly well worth achieving, and this seems to get us there.

```yaml
name: 'Iter8 Install'
description: 'Install Iter8 CLI'
runs:
  using: 'composite'
  steps:
    - name: Install Iter8 CLI
      env:
        VERSION: ${{ github.action_ref }}
      run: | 
        # For details on context variables runner.os and runner.arch, see:
        #    https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
        # The returned values do not match those used by the build artifacts. 
        # See https://github.com/iter8-tools/iter8/blob/master/Makefile#L4 (and for other valid combinations: https://github.com/mitchellh/gox/blob/master/platform.go#L28-L101)
        # Therefore, this code trasforms the context variables as follows:
        #   os: Linux -> linux, Windows -> windows, macOS -> darwin
        #   arch: X86 -> 386 amd X64 -> amd64
        OS=$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]' | sed 's/macos/darwin/')
        ARCH=$(echo ${{ runner.arch }} | sed 's/X86/386/' | sed 's/X64/amd64/')
        
        RELEASE="${{ env.VERSION }}"
        if [ -z $RELEASE ] || [ $RELEASE = "stable" ]; then
          REL=$(curl -s "https://api.github.com/repos/iter8-tools/iter8/releases/latest" | jq -r '.tag_name')
        fi
        if [ -z $REL ]; then
         REL=$(curl -s "https://api.github.com/repos/iter8-tools/iter8/tags" | jq --arg RELEASE $RELEASE -r '.[] | select(.commit.sha==$RELEASE) | .name')
        fi
        if [ -z $REL ]; then
          REL=$(curl -s "https://api.github.com/repos/iter8-tools/iter8/releases" | jq -r '.[] | .tag_name' | grep $RELEASE | head -1)
        fi
        if [ -z $REL ]; then
          echo "Invalid release specified: $RELEASE"
          exit 1
        fi
        echo "Installing Iter8 version $REL"

        ASSET="iter8-$OS-$ARCH.tar.gz"
        ASSET_URL="https://github.com/iter8-tools/iter8/releases/download/$REL/$ASSET"
        echo "Downloading $ASSET_URL"
        wget -q $ASSET_URL && rc=$? || rc=$?
        if [ $rc -eq 0 ]; then
          # echo "SUCCESS: downloaded $ASSET from $ASSET_URL"
          tar -xvf $ASSET
          mv $OS-$ARCH/iter8 /usr/local/bin
        else
          echo "ERROR: unable to download $ASSET from $ASSET_URL"
          exit 1
        fi
      shell: bash
branding:
  icon: check-circle
  color: green
```

FYI... @kalantar

Some finer points:

1. I removed the `sort` in the above commands -- the GitHub APIs already list results in the reverse chronological order. The sort was breaking this (and making earlier pre-release versions show at up at the top of the list).
2. I further simplified the first `if` where we are fetching the latest release.

2022-12-02 11:44 UTC, chgl commented
Sounds good to me! I'll get to it in a couple hours. Really like the solution!

2022-12-02 17:35 UTC, sriumcp approved these changes
lgtm

2022-12-02 18:24 UTC, kalantar approved these changes
lgtm

2022-12-02 18:37 UTC, merged