Events
iter8-tools/iter8 pull request #1446
Opened 2023-04-13 13:23 UTC by Alan-Cha

Fix #1434

2023-04-13 13:45 UTC, Alan-Cha commented on controllers/allcontrollers.go
> +	eventRecorder.Event(pod, eventtype, reason, message)
Event refers to a runtime object

2023-04-13 14:43 UTC, kalantar commented on controllers/allcontrollers.go
> +		log.Logger.Errorf("could not get pod namespace from environment variable %s", podNamespaceEnvVariable)
I'm inclined to think these should be info level statements. warning at most. if we fail to issue an event, I wouldn't call it an error.

2023-04-18 03:17 UTC, Alan-Cha commented on controllers/finalizer.go
> +	r, err2 := client.Resource(schema.GroupVersionResource{
I tried to use metadata instead of querying for the real object but I could not get it to work as expected.

2023-04-18 13:45 UTC, sriumcp requested changes
Minor change requested.

2023-04-18 13:45 UTC, sriumcp commented on controllers/routemap.go
> +										broadcastEvent(obj, corev1.EventTypeWarning, "Failed to apply template to routemap", "Failed to apply template to routemap", client)
Not so much "apply template to routemap" ... "apply template specified in routemap".

2023-04-18 17:39 UTC, Alan-Cha commented on controllers/finalizer.go
> +	}
Delete finalizer?

2023-04-20 00:44 UTC, sriumcp approved these changes
lgtm

2023-04-20 00:45 UTC, merged