Reorganize Kustomize traffic files
iter8-tools/iter8 pull request #1481
Opened 2023-05-19 17:41 UTC by Alan-Cha

Fix #1476

2023-05-19 20:46 UTC, Alan-Cha commented on kustomize/traffic/clusterScoped/kustomization.yaml
> +    kind: RoleBinding
I had some trouble patching the `kind`. Seems like certain methods of patching do no like the `kind` being changed. This method seems to work, however.

2023-05-23 13:48 UTC, kalantar requested changes

2023-05-23 13:48 UTC, kalantar commented on kustomize/traffic/clusterScoped/kustomization.yaml
I think we need to add:

`namespace: default`

2023-05-23 13:48 UTC, kalantar commented on kustomize/traffic/namespaceScoped/kustomization.yaml
> +namespace: default
I think we should remove this line so that it will install in the namespace set in the current kubernetes context.

2023-05-23 13:48 UTC, kalantar commented on kustomize/traffic/clusterScoped/kustomization.yaml
This will install it everything in the `default` namespace only when `clusterScoped` is used.

2023-05-23 14:23 UTC, kalantar approved these changes
lgtm

2023-05-24 13:42 UTC, merged