HTTP Grafana
iter8-tools/iter8 pull request #1562
Opened 2023-07-21 20:54 UTC by Alan-Cha

2023-07-21 21:00 UTC, Alan-Cha commented
Fixes #1537
Fixes #1538
Fixes #1547
Fixes #1548
Fixes #1549
Fixes #1550
Fixes #1551

2023-07-27 17:53 UTC, kalantar requested changes

2023-07-27 17:53 UTC, kalantar commented on charts/iter8/values.yaml
> +### resources are the resource limits for the pods
No need to add this since we moved to Grafana.

2023-07-27 17:53 UTC, kalantar commented on driver/kubedriver_test.go
Not clear that this is needed.

2023-07-27 17:53 UTC, kalantar commented on base/experiment.go
> +	Metadata ExperimentMetadata
add go tags `json:"" yaml:""`

2023-07-27 17:53 UTC, kalantar commented on base/collect_http.go
> +func (t *collectHTTPTask) getFortioResults() (map[string]fhttp.HTTPRunnerResults, error) {
since we are attempting to keep the old functionality, I think it better to leave the data structure the same.

2023-07-27 17:53 UTC, kalantar commented on base/collect_http.go
> +	// if t.With.Warmup != nil && *t.With.Warmup {
do this

2023-07-27 17:53 UTC, kalantar commented on metrics/server.go
> +type httpEndpointPanel struct {
`httpEndpointRow` ?

2023-08-03 14:02 UTC, closed without merging