Slack
iter8-tools/iter8 pull request #701
Opened 2021-05-27 14:32 UTC by kalantar

Documentation for https://github.com/iter8-tools/iter8/issues/689

2021-06-01 17:41 UTC, sriumcp requested changes
Minor changes requested.

2021-06-01 17:41 UTC, sriumcp commented on mkdocs/docs/reference/tasks/notification.md
> +The `notification/slack` task posts a slack message about current state the experiment.
of the experiment

2021-06-01 17:41 UTC, sriumcp commented on mkdocs/docs/reference/tasks/notification.md
> +The following task in the start action of an experiment creates a notification that will be posted to the slack channel with id `channel` during the execution of the `start` action.
The following task creates a notification (I realize start action is described in this example, but I feel is better to simply describe the task and leave out the action). This task is embeddable into start, loop or finish actions.

2021-06-02 17:56 UTC, kalantar commented
Replaced by https://github.com/iter8-tools/iter8/pull/729

2021-06-02 17:56 UTC, closed without merging