Builtin metrics
iter8-tools/iter8 pull request #732
Opened 2021-06-04 21:11 UTC by sriumcp

Partly addresses #684

2021-06-07 12:21 UTC, kalantar commented on mkdocs/docs/reference/tasks/metrics.md
> +The `metrics/collect` takes enables collection of [builtin metrics](). It generates a stream of HTTP requests to one or more app/ML model versions, and collects latency/error metrics.
missing link

2021-06-07 12:22 UTC, kalantar commented on mkdocs/docs/reference/tasks/metrics.md
> +| versions | [][Version](#version) | A non-empty list of versions. | Yes |
you added a parameter `loadOnly`

2021-06-07 12:24 UTC, kalantar requested changes
minor changes. Also I see  mkdocs/docs/metrics/builtin.md is an empty file. Is this intended?

2021-06-07 13:03 UTC, sriumcp commented
@kalantar Sorry, this one is not yet ready for review :) I should have made this into a draft... doing so now. Will be able to submit this for review shortly (and will address all your comments hopefully by then).

2021-06-08 13:23 UTC, huang195 commented
@sriumcp Is there no way to break this PR into smaller chunks? I'm looking at all the changes, and it's kind of difficult for me to understand how all the changes are related and be able to review them. If there's no clear way to break them into smaller pieces, then that's fine. It will just take longer to review the changes.

2021-06-08 13:37 UTC, sriumcp commented
@kalantar @huang195 Let me break it up into multiple chunks as suggested. I will convert  this into draft meanwhile to facilitate this.

2021-06-09 15:16 UTC, sriumcp commented
@kalantar This one is ready for review.

2021-06-09 16:24 UTC, kalantar submitted a review, later dismissed
Approved but recommend changing name of PR. It no longer hand to do with builtin metrics.

2021-06-09 16:44 UTC, sriumcp commented
@kalantar PR renamed.

2021-06-09 16:44 UTC, merged